ruby/rails-demo/config/routes.rb
Rails.application.routes.draw do
  root 'credit_cards#new'
  get 'credit_cards/new'
  post 'credit_cards/checkout'
end

ruby/rails-demo/app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :token
  belongs_to :customer
end

ruby/rails-demo/app/models/charge.rb
class Charge < ActiveRecord::Base
  belongs_to :token
  belongs_to :customer
  has_one :card

  validates :amount,   presence: true
  validates :currency, presence: true

  # If a customer is present use it to charge otherwise use a one-time-token
  # Omise Tokens can only be used once to charge, but it be saved as a customer
  def charge
    args = { amount: amount, currency: currency }
    if token.present?
      args[:card] = token.token
    elsif (customer && customer.cards.any?)
      args[:customer] = customer.remote_id
    else
      return false
    end
    charge!(args)
  end

  private

  def charge!(args)
    remote_response = Omise::Charge.create(args)
    store_charge(remote_response)
  end

  def store_charge(remote_response)
    remote_attr = remote_response.attributes.symbolize_keys
    self.card = Card.new(card_data: remote_attr[:card].symbolize_keys)
    self.response = remote_attr
    self.authorized = remote_attr[:authorized]
    self.captured = remote_attr[:captured]
    save
  end

end

ruby/rails-demo/app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :charges
  has_many :cards

  def from_token(token)
    response = Omise::Customer.create({
      email: self.email,
      description: self.description,
      card: token.remote_id
    })
    self.location = response.attributes["location"]
    self.remote_id = response.attributes["id"]
    self.default_card_id = response.attributes["default_card"]
    self.cards << token.card
    save
  end

end

ruby/rails-demo/app/models/token.rb
class Token < ActiveRecord::Base
  has_one :charge
end

ruby/rails-demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby/rails-demo/app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController

  def new
  end

  # Example Charge for 100.00 THB
  def checkout
    @charge = Charge.new(token: Token.new(token: params[:omise_token]), amount: 10000, currency: 'thb')
    @charge.charge
  end

end

ruby/rails-demo/app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

ruby/rails-demo/app/views/credit_cards/checkout.html.erb
<h3>Charge Results</h3>
<ul>
  <li>Amount: <%= (@charge.amount/100.0).round(2) %> <%= @charge.currency %></li>
  <li>Authorized: <%= @charge.authorized %></li>
  <li>Captured: <%= @charge.captured %></li>
</ul>

<h3>Card Details</h3>
<ul>
  <li>Omise ID: <%= @charge.card.card_data["id"] %></li>
  <li>Fingerprint: <%= @charge.card.card_data["fingerprint"] %></li>
  <li>Name: <%= @charge.card.card_data["name"] %></li>
  <li>Last Digits: <%= @charge.card.card_data["last_digits"] %></li>
  <li>Brand: <%= @charge.card.card_data["brand"] %></li>
  <li>Country: <%= @charge.card.card_data["country"] %></li>
  <li>Type: <%= @charge.card.card_data["financing"] %></li>
</ul>

ruby/rails-demo/app/views/credit_cards/new.html.erb
<%= form_tag(credit_cards_checkout_path, method: "post", id: "checkout") do %>
  <div id="token_errors" class=""></div>
  <input type="hidden" name="omise_token">
  <div class="row">
    <div class="col-xs-12">
      <div><label>Card Name</label><input type="text" data-omise="name" value="Omise Team"></div>
      <div><label>Card Number</label><input type="text" data-omise="number" value="4242424242424242"></div>
      <div><label>Expire Date</label>
        <input type="text" data-omise="expiration_month" size="2" value="11"> /
        <input type="text" data-omise="expiration_year" size="6" value="2020">
      </div>
      <div><label>Security Code</label><input type="text" data-omise="security_code" size="8" value="123"></div>
      <span class="omise-circle" style=""></span>
    </div>
  </div>
  <%= submit_tag "Checkout", id: "create_token" %>
<% end %>

<%= javascript_include_tag 'omise' %>

ruby/rails-demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsDemo</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'https://cdn.omise.co/omise.min.js.gz' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="content">
    <div class="logo"><%= image_tag("https://omise-cdn.s3.amazonaws.com/artwork/secured_by_omise_bodered.png") %></div>
    <%= yield %>
  </div>

</body>
</html>